{% set version = "1.4.9" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-apcluster
  version: {{ version|replace("-", "_") }}

source:
  url:
    - https://cran.r-project.org/src/contrib/apcluster_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/apcluster/apcluster_{{ version }}.tar.gz

  sha256: 3aac75e3e640eb89c1337d6f2e72a85d226b9c9483e43e0c76f9d424e758cb72

build:
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - posix                # [win]
    - {{ compiler('c') }}        # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ compiler('cxx') }}        # [unix]
    - {{ compiler('m2w64_cxx') }}  # [win]
  host:
    - r-base
    - r-matrix
    - r-rcpp >=0.11.1
  run:
    - r-base
    - r-matrix
    - r-rcpp >=0.11.1

test:
  commands:
    - $R -e "library('apcluster')"  # [not win]
    - "\"%R%\" -e \"library('apcluster')\""  # [win]

about:
  home: https://cran.r-project.org/web/packages/apcluster/index.html
  license: GPL (>= 2)
  summary: Implements Affinity Propagation clustering introduced by Frey and Dueck (2007) <DOI
  license_family: GPL3
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3
extra:
  recipe-maintainers:
    - conda-forge/r
    - MathiasHaudgaard
    - FrodePedersen
    - ArneKr
