# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_r_base3.4.1
    - CONFIG=osx_r_base3.5.1

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "eyh/ib3xbo6VRRKlkb79bsNGZbeAxZGuyHB/eC8CS83kL51ivjTd281Q3X+0p4BibDXVe9aLGNS4IXxZ4MLn3C0n4CSfjeskMM7X2oZt5C6EqIpBmJGne9gFzJoRKzRjIfjiycitwziAhsS6ifB9/GZfVr4Bs9ozVv+n1+NI8vj1sTfOtxfSkW+/0+pg1VxYkJPBUiBIbZjN1Kuio1Aw3Al3o48KzuvoZpqcdDKEL9Th3BeGClMC6nnUZfLrg/SCPIBKXlxkRZYDK2he1l6n9MpAGAZMGhtp+ceYja8Aq1pY7eQB50mn9dNZBzyNzri24YFjTbr2jnf6RTo1CAk8yTztwt3I2i6kocrQlQy0tBtagZqEPIF8+7ZcubFwH27Je/9EsR+cXkL9uibCkUiwacVQKLm6JPgKwQEMNmxLsHQAeEdZxIcKZnk1Evku40VIJIEd3Ftc54BdEkUscHICE+TwuttGFeriL929Db1/KBiHuE8xo15ssHwfGh7TmFXbqOaA2/L9KKSHgjENLkKic84YqxEQ2khWiWUVPqtap6wET3v/6lQeQGuQNJG/+jbazsHGdhGvePCQwN68iFmc3nM73tS7qeh9Nn/m6oEAPE131i8IBFLPIEBFG+qvO3RLFoe9k8Y+Yvkt90qFmapD5CZaeZKZVE9/4vvQ2uCN0zY="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
