travis:
  secure:
    BINSTAR_TOKEN: uRc9bO+4Gmip0v9R+I8saA03fpvuBiyQttrxH9gNoF3pZMdLSGwGD3j8bvpidI3rDqsVhW86+NUSWtG43NIYTo2B6wB5E7GZ/3YLdarAX2B7XdAAKR9uitjN0Xr7eTxAdj7Unk94hN1GeD0N4xjssmAX9g8VHlhbuc7xv2B/sgn+VMy7RjjSaPgJhdISejpNCsxV/xfIkdeieFjVr1aKZ+HFTZUdzqcWWDGhaV33u33ZhFEkLw9fZfhTkR5g8PFFkhRRD6Yu8q26EYdC5LYXT3SE6s/9SVHlJbrkVEvjkel86nOYCO6LPogjDF/zZtnNtGn7d88ZslZWbZWD/h91ReyV4LwDj9mf5YM5aQmJScoa1mI/AmHUz7k+CaM9vxz47ofsg5oIX0EYjGOeCAPFsdAwdlQQIathWL7PEHyZjtc2K9mkg+Ye/yEHEN3iogZUpTPShy78i0XWHv0KjrdNie8CgeiJJJELub8EamMkT043Pw7+T7W1pajFx6EgUF3RNdsUvi6ssn/XZKdqgTdaaBmUDDWOJ4oG0jM0cDx3udEUH/7L2w5WZh6UUpDCsQaSkkP6qsytrRqs3R91AHK31uX9sq+5IUjbSwlQpsN4vBNMh9oqFiosJ1DksDzaNcwCa+XHu9hL0r2gQGVXr6oKLAKfH+f0VNVhkpxzVgyqAPE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
