travis:
  secure:
    BINSTAR_TOKEN: FE8v3K+4TT4Q1hLSPLazcMctqmupFz50kXLisYXhdHhmFrJdcMpc5mnGJYRkPSulnTvCTeMiJxzhg4RrW8yl5W2g/+eyUsoh0am5P/xaAJ+3I/IuRDNn3ovnJgF4as1iPH1L2wyq9CDXm1Z8mpVmyMhfTezDvuDo9/JJYRNcpRmXIYLYRvQEKK6pbGaCXrMlw0scaZ+320R6iUEo6rGNSOUZcDCHbb7hKPjHLw3dqBfutj6zklH++GXN1uYa8mOCr8+VA8mO7uZ0tQ3hsiMW4quzEMh/myPO/KVqPyjuNPokDGkM+n6MDawj24p0msnwUVxjkOteChoxhx7bxZ8/tGxffxvpK+PK9z1Rk6A8ehoV97RStpLYLc827ejorLTb4gSZMQ9OZtLdvygykJ+yiMHmdhOfiE36hSnpY9mg57QjHzsLon0LJ25iC2QIO3vNyIqDI+9nRqge1z6/Xo56DtK1CdP92iZMDozri+Y0Kb10uNv+LupqP8Wd9XupP/2N2AotNJx8oj0/ndTTpV/Pa0EeTMn1NJm9+4hmzi0lO/sYxUUWfiSTrxcteJYkRzTR36p9ZHKfclhRrDN98dieMF5SrFre96CXPqjH0zAkNOc6ovbcnSqiX/NRgRA2e0L+0BypoZyPEtxzong5bqH91XG5EYABoWL0bD6hSTkDuvI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
