appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: eyh/ib3xbo6VRRKlkb79bsNGZbeAxZGuyHB/eC8CS83kL51ivjTd281Q3X+0p4BibDXVe9aLGNS4IXxZ4MLn3C0n4CSfjeskMM7X2oZt5C6EqIpBmJGne9gFzJoRKzRjIfjiycitwziAhsS6ifB9/GZfVr4Bs9ozVv+n1+NI8vj1sTfOtxfSkW+/0+pg1VxYkJPBUiBIbZjN1Kuio1Aw3Al3o48KzuvoZpqcdDKEL9Th3BeGClMC6nnUZfLrg/SCPIBKXlxkRZYDK2he1l6n9MpAGAZMGhtp+ceYja8Aq1pY7eQB50mn9dNZBzyNzri24YFjTbr2jnf6RTo1CAk8yTztwt3I2i6kocrQlQy0tBtagZqEPIF8+7ZcubFwH27Je/9EsR+cXkL9uibCkUiwacVQKLm6JPgKwQEMNmxLsHQAeEdZxIcKZnk1Evku40VIJIEd3Ftc54BdEkUscHICE+TwuttGFeriL929Db1/KBiHuE8xo15ssHwfGh7TmFXbqOaA2/L9KKSHgjENLkKic84YqxEQ2khWiWUVPqtap6wET3v/6lQeQGuQNJG/+jbazsHGdhGvePCQwN68iFmc3nM73tS7qeh9Nn/m6oEAPE131i8IBFLPIEBFG+qvO3RLFoe9k8Y+Yvkt90qFmapD5CZaeZKZVE9/4vvQ2uCN0zY=
conda_forge_output_validation: true
